# No Response Action.
#
# This action will closes issues where the original author doesn't respond to a request for information. We have it to remove the need for maintainers to remember to check back on issues periodically to see if contributors have responded.
#
# Source: https://github.com/lee-dohm/no-response
name: 'No Response'

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 6,18 * * *' # Every day at 6:00 AM and 6:00 PM

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          daysUntilClose: 14 # Number of days of inactivity before an Issue is closed for lack of response
          responseRequiredLabel: "needs: author feedback" # Label indicating that a response from the original author is required
          closeComment: >
            This issue has been automatically closed because there has been no response
            to our request for more information after 14 days. Please reopen if you can provide the
            requested information. See [this blog post](https://www.lee-dohm.com/2015/01/04/writing-good-bug-reports/)
            for tips on how to write effective bug reports.
