name: 'Process stale issues'

on:
  schedule:
    - cron: '21 0 * * *'
  workflow_dispatch:

permissions: {}

jobs:
    stale:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: write
            pull-requests: write
        steps:
          - name: Process stale issues
            uses: actions/stale@v9.0.0
            with:
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                stale-issue-message: "As a part of this repository's maintenance, this issue is being marked as stale due to inactivity. Please feel free to comment on it in case we missed something.\n\n###### After 14 days with no activity this issue will be automatically be closed."
                close-issue-message: 'This issue was closed because it has been 14 days with no activity.'
                operations-per-run: 140
                days-before-stale: -1
                days-before-close: -1
                days-before-issue-stale: 14
                days-before-issue-close: 14
                stale-issue-label: 'status: stale'
                stale-pr-label: 'status: stale'
                exempt-issue-labels: 'type: enhancement'
                only-issue-labels: 'needs: author feedback'
                close-issue-label: "status: can't reproduce"
                ascending: true
