name: Sync Labels to Repository

on: [issues, pull_request]

jobs:
    sync-labels:
        runs-on: ubuntu-latest
        name: Sync repository labels
        steps:
        - uses: cocart-headless/wp-repo-labels@v1
        with:
        labels-path: ./.github/labels.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
