name: Sync Labels to Repository

on: [issues, pull_request]

jobs:
  sync-labels:
      runs-on: ubuntu-latest
      steps:
        - name: Sync repository labels
          uses: cocart-headless/wp-repo-labels@v1
          with:
            labels-path: ./.github/labels.json
            github-token: ${{ secrets.GITHUB_TOKEN }}
