name: Test Release Trigger

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Release Event
        run: |
          echo "Release triggered!"
          echo "Tag: ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Published: ${{ github.event.release.published_at }}"