name: 'Update contributor feedback labels on comment'

on: 'issue_comment'

permissions: {}

jobs:
    feedback:
      if: |
        github.actor != 'github-actions' &&
        github.actor == github.event.issue.user.login &&
        github.event.issue &&
        github.event.issue.state == 'open' &&
        contains(github.event.issue.labels.*.name, 'needs: author feedback')
      runs-on: ubuntu-latest
      permissions:
        issues: write
      steps:
      - name: Add has feedback
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'needs: triage feedback'
      - name: remove needs feedback
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'needs: author feedback'
      - name: remove stale
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'status: stale'
